config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'check_out/form'
  get 'check_out/complete'

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :check_out, only: [:form, :complete]

  devise_for :users
  
  root to: 'welcome#index'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def total_qty
    order_items.collect { |oi| oi.valid? ? (oi.quantity) : 0 }.sum
  end

private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base  
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/check_out_controller.rb
class CheckOutController < ApplicationController
  def form
  	@order_items = current_order.order_items
  end

  def complete
  	@order_items = current_order.order_items.destroy_all
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
  
private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/check_out_helper.rb
module CheckOutHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">
  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
      <p><small><%= product.description %></small></p>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1, max: order_item.product.stocks %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <div class="starter-template">
    <p class="text-center">
      There are no items in your shopping cart.  Please <%= link_to "go back", 'products#index' %> and add some items to your cart.
    </p>
  </div>
<% else %>
  <p class="text-center"><%= link_to "Click here to return to the shop.", 'products#index' %></p>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
  <p class="text-right">You have <%= current_order.order_items.size %> item(s) in your cart.</p>
  <h3 class="text-right">Subtotal: <span style="color: green"><%= number_to_currency current_order.subtotal %></span></h3>
  <p class="text-center"><a type="button" class="btn btn-success btn-lg" href="\check_out\form.html" role="button">Proceed to Check Out</a></p>
  <p class="text-center"><%= link_to "Click here to return to the shop.", 'products#index' %></p>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/check_out/_check_out_row.html.erb
<div class="container">
	<div class="row">
		<hr>
		<h4><%= product.name %></h4>
		<p><small><%= product.description %></small></p>
		<%= form_for order_item, remote: true do |f| %>
			<p>Unit Price: <%= number_to_currency order_item.unit_price %></p>
			<p>Quantity: <%= order_item.quantity %></p>
			<p>Total Price for this item: <span style="color: green"><%= number_to_currency order_item.total_price %></span></p>
		<% end %>
	</div>
</div>

app/views/check_out/complete.html.erb
<h1 class="text-center">Check out successful!</h1>
<h4 class="text-center">Thank you for shopping with Nuggalopes and Friends!</h4>
<p class="text-center"><%= link_to "Return to store", '\products#index' %></p>

app/views/check_out/form.html.erb
<div class="container">
	<h3 class="text-center">Check Out</h3>
	<% if !@order_item.nil? && @order_item.errors.any? %>
	  <div class="alert alert-danger">
	    <ul>
	    <% @order_item.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<% if @order_items.size == 0 %>
	  <div class="starter-template">
	    <p class="text-center">
	      There are no items in your shopping cart.  Please <%= link_to "go back", 'products#index' %> and add some items to your cart.
	    </p>
	  </div>
	<% else %>
	  <p>Hello, <strong><%= current_user.email %></strong>!
	  	<br>Here is a summary of your order:</p>
	  <% @order_items.each do |order_item| %>
	    <%= render 'check_out/check_out_row', product: order_item.product, order_item: order_item, show_total: true %>
	  <% end %>
	  <hr>
	  <p class="text-right">You are purchasing a total of <%= current_order.total_qty %> item(s).</p>
	  <h3 class="text-right">Subtotal: <span style="color: green"><%= number_to_currency current_order.subtotal %></span></h3>
	  <hr>
	  <h3>Billing Information</h3>
	  <form>
	  	Full Name:<br>
		<input type="text" size="25">
		<br>
		Billing Address:<br>
		<textarea cols="40" rows="5"></textarea>
		<br>
	  	Shipping Address:<br>
	  	<textarea cols="40" rows="5"></textarea>
	  	<br>
	  	Contact Number:<br>
	  	<input type="text" size="25">
		<br>
	 	Credit Card Number:<br>
	 	<input type="text" size="25">
		<br>
	  	Security Code:<br>
	  	<input type="text" size="25">
		<br>
	  </form>
	  <hr>
	  
	  <div class="text-center">
	  	<%= button_to "Complete Order",  { action: "complete", id: @check_out, method: :complete, data: { confirm: "Are you sure?" } }, :method => :get, class: "btn btn-success" %>
	  	<br>
	  	<%= link_to "Click here to return to the shop.", 'products#index' %>
	  </div>
	   
	<% end %>
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Item(s) in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
   		<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">

	 	<title>Nuggalopes and Friends</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

		<link href="/assets/bootstrap.min.css" rel="stylesheet">
		<link href="/assets/custom.css" rel="stylesheet">
	</head>

	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<nav>
						<ul class="nav pull-right">
							<% if user_signed_in? %>
								<li class="dropdown">
									<a href="#" class="dropdown=toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
									<ul class="dropdown-menu" role="menu">
										<li><a href="/#">Home</a></li>
										<li class="cart-text"><%= render 'layouts/cart_text' %></li>
										<li class="divider"></li>
										<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
										<li><%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
									</ul>
								</li>
							<% else %>
								<li><a href="/#">Home</a></li>
								<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
								<li><%= link_to "Log in", new_user_session_path, :class => 'navbar-link'  %></li>
							<% end %>
						</ul>
					</nav>
				</div>
			</div>
		</nav>

		<div class="container">
			<%= yield %>
		</div>

		<footer class="footer">
			<div class="starter-template">
				<hr>
				<small>
					<% if user_signed_in? %>
						You're logged in as <strong><%= current_user.email %></strong>.<br><br>
					<% end %>
					<%= link_to "Store Home", '\#' %>
					<% if user_signed_in? %>
						&nbsp;|&nbsp;&nbsp;<%= link_to "Your Cart", cart_path %>&nbsp;&nbsp;|&nbsp;&nbsp;<%= link_to "Sign out?", destroy_user_session_path, method: :delete %>
					<% else %>
						|&nbsp;<%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Log in", new_user_session_path %>
					<% end %>
				</small>
			</div>
		</footer>
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    	<!-- Include all compiled plugins (below), or include individual files as needed -->
    	<script src="/assets/bootstrap.min.js"></script>
	</body>
</html>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="well">
  <div class="row">
    <div class="col-md-8">
      <h4><%= product.name %></h4>
      <p><small><%= product.description %></small></p>
    </div>

    <div class="col-md-4">
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>

        <% if user_signed_in? %>
          <div class="input-group">
            <%= f.number_field :quantity, value: 1, class: "form-control", min: 1, max: product.stocks %>

            <div class="input-group-btn">
              <%= f.hidden_field :product_id, value: product.id %>
              <%= f.submit "Add to Cart", :onclick => "alert('Added to cart!')", class: "btn btn-primary" %>
            </div>
          </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
	<h3 class="text-center">Our friends below need a new home.</h3>

	<div class="row">
	  <div class="col-xs-6 col-xs-offset-3">
	    <% @products.each do |product| %>
	      <%= render "product_row", product: product, order_item: @order_item %>
	    <% end %>
	  </div>
	</div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="starter-template">
	<h1>Welcome to Nuggalopes and Friends!</h1>
	<p class="lead">We sell regular nugs, giant nugs and many other things.</p>
	<p class="text-center"><a class="btn btn-lg btn-success" href="products#index" role="button">Take me to the shop!</a></p>
</div>